### ISSUE TITLE
Alert: Unhandled error, Request failed with status code 404

### ISSUE THREAD

**Issue by giorgiosironi** [hivereview/thehive#248]
```
Error: Request failed with status code 404
at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
at IncomingMessage.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1252:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by giorgiosironi** [comment]
Can reproduce with:
http://localhost:8080/articles/10.1101/2020.09.03.281097

**Comment by giorgiosironi** [comment]
Produces a 500:
```
app_message | Sent HTTP response
-- | --
app_payload.requestId | c0e0d600-fcb2-11ea-9761-f5b1a1a90ba1
app_payload.status | 500
```

**Comment by giorgiosironi** [comment]
We have 4 reviews on file:
```
$ grep -r 10.1101/2020.09.03.281097 data/
data/reviews/316db7d9-88cc-4c26-b386-f067e0f56334.csv:2020-09-21T07:13:43.122155+00:00,10.1101/2020.09.03.281097,hypothesis:-1qhAPvZEeqY_iNoG0p4hQ
data/reviews/316db7d9-88cc-4c26-b386-f067e0f56334.csv:2020-09-21T07:13:42.882862+00:00,10.1101/2020.09.03.281097,hypothesis:-zdMlvvZEeqzEQegRrq-bA
data/reviews/316db7d9-88cc-4c26-b386-f067e0f56334.csv:2020-09-21T07:13:41.891165+00:00,10.1101/2020.09.03.281097,hypothesis:-qHrOPvZEeq-voPUE3EMRw
data/reviews/316db7d9-88cc-4c26-b386-f067e0f56334.csv:2020-09-21T07:13:41.459222+00:00,10.1101/2020.09.03.281097,hypothesis:-lqbhPvZEeqj4U-eZd_Bhg
```
but https://www.biorxiv.org/content/10.1101/2020.09.03.281097v1# only shows 2 with the text:
```
Test post against https://doi.org/10.1101/...
```
as probably the other 2 have been deleted by Review commons. As a result the whole page fails.

**Comment by giorgiosironi** [comment]
Looks like all 4 of our values are now deleted.

**Comment by giorgiosironi** [comment]
`fetch-hypothesis-annotations` current `Review` type can accomodate missing `publicationDate` or `summary`, but not a missing URL that we need to lookup through the API (and even if we had one, it would lead to a 404).

Running `make update-event-data` to try to fix the data, a decision is needed on what to do with disappearing reviews. Same error happened with eLife, but we don't have a related issue with details because the alert was on Miro and got deleted.

**Comment by giorgiosironi** [comment]
http://localhost:8080/articles/10.1101/2020.09.03.281097 now works but we only picked up one review of the two listed at https://www.biorxiv.org/content/10.1101/2020.09.03.281097v1# 
They are fake content anyway.

**Comment by giorgiosironi** [comment]
Needs https://github.com/hivereview/thehive/issues/250 to be fully addressed.
