### ISSUE TITLE
Unhandled Error following crossref 504

### ISSUE THREAD

**Issue by erkannt** [hivereview/thehive#287]
UX goal:

- each feed item errors -> show error msg at feed item in feed
  - show as much info as possible
  - 'Community reviewed an article'

- [x] tests
- [x] handle reviews
- [x] handle endorsements

```
Error: Tried to `unsafelyUnwrap an Err`
at Err.unsafelyUnwrap (/app/node_modules/true-myth/dist/cjs/result.js:305:15)
-> /app/node_modules/true-myth/dist/cjs/result.ts:444:11
at getArticleAdapter (/app/build/home-page/index.js:25:77)
-> /app/src/home-page/index.ts:48:36
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async renderEditorialCommunityReviewedArticle (/app/build/home-page/render-feed-item.js:17:25)
-> /app/src/home-page/render-feed-item.ts:47:21
at async /app/build/home-page/render-feed-item.js:40:13
-> /app/src/home-page/render-feed-item.ts:81:13
at async Promise.all (index 10)
at async /app/build/home-page/render-feed.js:34:31
-> /app/src/home-page/render-feed.ts:44:27
at async /app/build/home-page/render-page.js:8:13
-> /app/src/home-page/render-page.ts:18:13
at async /app/build/http/page-handler.js:19:18
-> /app/src/http/page-handler.ts:38:18
at async /app/build/http/identify-user.js:7:5
-> /app/src/http/identify-user.ts:11:5
```

**Comment by giorgiosironi** [comment]
![Screenshot_2020-10-13 The Hive](https://user-images.githubusercontent.com/160299/95842309-4d3e6400-0d3e-11eb-8876-2951edb56ea5.png)
